### ISSUE TITLE
Looks interesting, but missing DBLoop stuff?!

### ISSUE THREAD

**Issue by DennisGaida** [spjeff/spupgradehelper#1]
In your documentation you include stuff about DBLoop like `DBLoop.ps1` - I can't find it in the repository? The Migration scripts themselves are less useful without those scripts as I believe they only wrap Mount/Dismount etc.  in functions with added logging/timing.

On Codeplex the DBLoop file exist :-)

**Comment by spjeff** [comment]
Sharp eye!  Thank you.

I downloaded those files from CodePlex and added to repo.

https://github.com/spjeff/spupgradehelper/commit/904ad32e308ae7229f3ce8fa94b79a59312231b5#diff-c9a9a46a90a501b7a423a842b4bb7a65
